# permissions for end users to edit gameservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gameserver-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: f11r-operator
    app.kubernetes.io/part-of: f11r-operator
    app.kubernetes.io/managed-by: kustomize
  name: gameserver-editor-role
rules:
- apiGroups:
  - game.believer.dev
  resources:
  - gameservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - game.believer.dev
  resources:
  - gameservers/status
  verbs:
  - get
