# permissions for end users to edit playtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: playtest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: f11r-operator
    app.kubernetes.io/part-of: f11r-operator
    app.kubernetes.io/managed-by: kustomize
  name: playtest-editor-role
rules:
- apiGroups:
  - game.believer.dev
  resources:
  - playtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - game.believer.dev
  resources:
  - playtests/status
  verbs:
  - get
